alter PROCEDURE [Tramite].[paListarPeriodoBusquedaExpediente]
AS
	BEGIN TRY
	SET LANGUAGE 'SPANISH'

	SELECT
		--DISTINCT
		YEAR(CONVERT(DATE,E.NTFechaExpediente)) IdPeriodo,
		convert(varchar(4),YEAR(CONVERT(DATE,E.NTFechaExpediente))) NombrePeriodo
		FROM
		Tramite.Expediente E
		where E.EstadoAuditoria=1
		group by YEAR(CONVERT(DATE,E.NTFechaExpediente))
		order by 1 desc
	END TRY
	BEGIN CATCH
			DECLARE @ERROR_NUMBER INT, @ERROR_SEVERITY INT,@ERROR_STATE INT,@ERROR_LINE INT,@ERROR_PROCEDURE VARCHAR(MAX)	,@ERROR_MESSAGE VARCHAR(MAX)
			SELECT @ERROR_NUMBER=ERROR_NUMBER() , @ERROR_SEVERITY=ERROR_SEVERITY() , @ERROR_STATE=ERROR_STATE() , @ERROR_PROCEDURE='Tramite.paListarPeriodoBusquedaExpediente',@ERROR_LINE=ERROR_LINE(),@ERROR_MESSAGE=ERROR_MESSAGE()
			EXEC Seguridad.paGuardarErroresEnLog @ERROR_NUMBER , @ERROR_SEVERITY , @ERROR_STATE ,  @ERROR_PROCEDURE,@ERROR_LINE,@ERROR_MESSAGE
	 END CATCH
