PRIORIDAD DE LOS SP - para pase a produccion:

1. Tramite.paListarExpedientePendienteEspecialistaCreados
2. Tramite.paListarExpedientePendienteEspecialistaV7
3. Tramite.paListarExpedientePendienteEspecialistaReenviados
4. Tramite.paListarExpedientePendienteEspecialistaArchivados
5. Tramite.paListarExpedientePendienteJefaturaTodosFosCad
6. Tramite.paObtenerEstadosExpedientesEspecialista
7. Tramite.paObtenerEstadosExpedientesJefatura
8. Tramite.paListarExpedientePendienteJefaturaPorRecibirFosCad
