Tramite.Expediente_Historico_2022
Tramite.ExpedienteDevuelto_Historico_2022
Tramite.ExpedienteEnlazado_Historico_2022
Tramite.ExpedienteSeguimiento_Historico_2022


Tramite.ExpedienteDocumento_Historico_2022
Tramite.ExpedienteDocumentoFirmante_Historico_2022
Tramite.ExpedienteDocumentoAdjunto_Historico_2022
Tramite.ExpedienteDocumentoAdjuntoFirmante_Historico_2022
Tramite.ExpedienteDocumentoAdjuntoTemporal_Historico_2022


Tramite.ExpedienteDocumentoOrigen_Historico_2022
Tramite.ExpedienteDocumentoOrigenAdjunto_Historico_2022

Tramite.ExpedienteDocumentoOrigenDestino_Historico_2022
Tramite.ExpedienteDocumentoOrigenDestinoAccion_Historico_2022
Tramite.ExpedienteDocumentoOrigenDestinoTemporal_Historico_2022


Tramite.NumeracionSeparada_Historico_2022


U    Tramite.Expediente
U    Tramite.ExpedienteDocumento
U    Tramite.ExpedienteEnlazado
U    Tramite.ExpedienteSeguimiento
U    Tramite.ExpedienteDocumentoAdjunto
U    Tramite.ExpedienteDocumentoOrigenAdjunto
U    Tramite.ExpedienteDocumentoFirmante



Tramite.ExpedienteDocumentoVisualizacion_Historico_2022
