
-- CREATE PROCEDURE [Tramite].[paListarExpedientePendienteEspecialistaPorRecibir]

SELECT
@pConFiltroFecha=0,
@pFechaInicio='13/04/2026',
@pFechaFin='13/04/2026',
@pConFiltroFechaMovimiento=0,
@pFechaInicioMovimiento='13/04/2026',
@pFechaFinMovimiento='13/04/2026',
@pIdPersona=590,
@pIdEmpleadoPerfil=588,
@pIdCatalogoSituacionMovimientoDestino=4,
@pTipoSituacionMovimiento=4,
@pIdAreaOrigen=0,
@pIdAreaDestino=0,
@pIdPeriodo=2026,
@pIdCatalogoTipoPrioridad=0,
@pIdCatalogoTipoTramite=0,
@pIdCatalogoTipoDocumento=0,
@pNumeroExpediente='',
@pNumeroDocumento='',
@pPersonaDesde='',
@pPersonaPara='',
@pIdTipoIngreso=0,
@pFechaDocumento='',
@pEmisorExpediente='',
@pAsuntoExpediente='',
@pIdUsuarioAuditoria=590,
@pCampoOrdenado=NULL,
@pTipoOrdenacion=NULL,
@pNumeroPagina=1,
@pDimensionPagina=100,
@pBusquedaGeneral=NULL,
@pFlgBusqueda=0

select
    @pConFiltroFecha= 0,
	@pFechaInicio= '10/04/2026',
	@pFechaFin= '10/04/2026',
	@pConFiltroFechaMovimiento= 0,
	@pFechaInicioMovimiento= '10/04/2026',
	@pFechaFinMovimiento= '10/04/2026',
	@pIdPersona= 1059,
	@pIdEmpleadoPerfil= 2259,
	@pIdCatalogoSituacionMovimientoDestino= 4,
	@pTipoSituacionMovimiento= 4,
	@pIdAreaOrigen= 0,
	@pIdAreaDestino= 0,
	@pIdPeriodo= 2026,
	@pIdCatalogoTipoPrioridad= 0,
	@pIdCatalogoTipoTramite= 0,
	@pIdCatalogoTipoDocumento= 0,
	@pNumeroExpediente= '',
	@pNumeroDocumento= '',
	@pPersonaDesde= '',
	@pPersonaPara= '',
	@pIdTipoIngreso= 0,
	@pFechaDocumento= '',
	@pEmisorExpediente= '',
	@pAsuntoExpediente= '',
	@pIdUsuarioAuditoria= 1059,
	@pCampoOrdenado= null,
	@pTipoOrdenacion= null,
	@pNumeroPagina= 1,
	@pDimensionPagina= 10,
	@pBusquedaGeneral= null,
	@pFlgBusqueda= 0



	-- CREATE PROCEDURE [Tramite].[paListarExpedientePendienteJefaturaPorRecibirFosCad]
select
		@pConFiltroFecha = 0,
		@pFechaInicio = '15/04/2026',
		@pFechaFin = '15/04/2026',
		@pConFiltroFechaMovimiento = 0,
		@pFechaInicioMovimiento = '15/04/2026',
		@pFechaFinMovimiento = '15/04/2026',
		@pIdArea = 30,
		@pIdCatalogoSituacionMovimientoDestino = 4,
		@pTipoSituacionMovimiento = 0,
		@pIdAreaOrigen = 0,
		@pIdAreaDestino = 0,
		@pIdPeriodo = 0,
		@pIdCatalogoTipoPrioridad = 0,
		@pIdCatalogoTipoTramite = 0,
		@pIdCatalogoTipoDocumento = 0,
		@pNumeroExpediente = '',
		@pNumeroDocumento = '',
		@pPersonaDesde = '',
		@pPersonaPara = '',
		@pIdTipoIngreso = 0,
		@pFechaDocumento = '',
		@pEmisorExpediente = '',
		@pAsuntoExpediente = '',
		@pIdUsuarioAuditoria = 52939,
		@pCampoOrdenado = null,
		@pTipoOrdenacion = null,
		@pNumeroPagina = 1,
		@pDimensionPagina = 10,
		@pBusquedaGeneral = null,
		@pFlgBusqueda = 0


 -- Tramite.paListarExpedienteMesaParteDespachadosV1
 select
 @pIdArea=20,
 @pIdUsuarioAuditoria=389,
 @pCampoOrdenado=NULL,
 @pTipoOrdenacion=NULL,
 @pNumeroPagina=1,
 @pDimensionPagina=10,
 @pBusquedaGeneral=NULL

 -- Tramite.paListarExpedienteMesaParteDespachadosV1 20, 389,null, null, 1,10,null
