
EXECUTE tramite.paListarExpedientePendienteJefaturaTodosFosCad
0,
'30/04/2026',
'30/04/2026',
0,
'30/04/2026',
'30/04/2026',
10,
0,
0,
0,
0,
2026,
0,
0,
0,
'','','','',0,'','','',53354,null,null,1,10,'031769',0

SELECT
@pConFiltroFecha = 0,
@pFechaInicio = '30/04/2026',
@pFechaFin = '30/04/2026',
@pConFiltroFechaMovimiento = 0,
@pFechaInicioMovimiento = '30/04/2026',
@pFechaFinMovimiento = '30/04/2026',
@pIdArea = 10,
@pIdCatalogoSituacionMovimientoDestino = 0,
@pTipoSituacionMovimiento = 0,
@pIdAreaOrigen = 0,
@pIdAreaDestino = 0,
@pIdPeriodo = 2026,
@pIdCatalogoTipoPrioridad = 0,
@pIdCatalogoTipoTramite = 0,
@pIdCatalogoTipoDocumento = 0,
@pNumeroExpediente = '',
@pNumeroDocumento = '',
@pPersonaDesde = '',
@pPersonaPara = '',
@pIdTipoIngreso = 0,
@pFechaDocumento = '',
@pEmisorExpediente = '',
@pAsuntoExpediente = '',
@pIdUsuarioAuditoria = 53354,
@pCampoOrdenado = null,
@pTipoOrdenacion = null,
@pNumeroPagina = 1,
@pDimensionPagina = 10,
@pBusquedaGeneral = '031769',
@pFlgBusqueda = 0


return

-- -- CREATE PROCEDURE [Tramite].[paListarExpedientePendienteEspecialistaPorRecibir]

-- SELECT
-- @pConFiltroFecha=0,
-- @pFechaInicio='13/04/2026',
-- @pFechaFin='13/04/2026',
-- @pConFiltroFechaMovimiento=0,
-- @pFechaInicioMovimiento='13/04/2026',
-- @pFechaFinMovimiento='13/04/2026',
-- @pIdPersona=590,
-- @pIdEmpleadoPerfil=588,
-- @pIdCatalogoSituacionMovimientoDestino=4,
-- @pTipoSituacionMovimiento=4,
-- @pIdAreaOrigen=0,
-- @pIdAreaDestino=0,
-- @pIdPeriodo=2026,
-- @pIdCatalogoTipoPrioridad=0,
-- @pIdCatalogoTipoTramite=0,
-- @pIdCatalogoTipoDocumento=0,
-- @pNumeroExpediente='',
-- @pNumeroDocumento='',
-- @pPersonaDesde='',
-- @pPersonaPara='',
-- @pIdTipoIngreso=0,
-- @pFechaDocumento='',
-- @pEmisorExpediente='',
-- @pAsuntoExpediente='',
-- @pIdUsuarioAuditoria=590,
-- @pCampoOrdenado=NULL,
-- @pTipoOrdenacion=NULL,
-- @pNumeroPagina=1,
-- @pDimensionPagina=100,
-- @pBusquedaGeneral=NULL,
-- @pFlgBusqueda=0

-- select
--     @pConFiltroFecha= 0,
-- 	@pFechaInicio= '10/04/2026',
-- 	@pFechaFin= '10/04/2026',
-- 	@pConFiltroFechaMovimiento= 0,
-- 	@pFechaInicioMovimiento= '10/04/2026',
-- 	@pFechaFinMovimiento= '10/04/2026',
-- 	@pIdPersona= 1059,
-- 	@pIdEmpleadoPerfil= 2259,
-- 	@pIdCatalogoSituacionMovimientoDestino= 4,
-- 	@pTipoSituacionMovimiento= 4,
-- 	@pIdAreaOrigen= 0,
-- 	@pIdAreaDestino= 0,
-- 	@pIdPeriodo= 2026,
-- 	@pIdCatalogoTipoPrioridad= 0,
-- 	@pIdCatalogoTipoTramite= 0,
-- 	@pIdCatalogoTipoDocumento= 0,
-- 	@pNumeroExpediente= '',
-- 	@pNumeroDocumento= '',
-- 	@pPersonaDesde= '',
-- 	@pPersonaPara= '',
-- 	@pIdTipoIngreso= 0,
-- 	@pFechaDocumento= '',
-- 	@pEmisorExpediente= '',
-- 	@pAsuntoExpediente= '',
-- 	@pIdUsuarioAuditoria= 1059,
-- 	@pCampoOrdenado= null,
-- 	@pTipoOrdenacion= null,
-- 	@pNumeroPagina= 1,
-- 	@pDimensionPagina= 10,
-- 	@pBusquedaGeneral= null,
-- 	@pFlgBusqueda= 0


-- EXECUTE Tramite.paListarExpedientePendienteJefaturaPorRecibirFosCad
-- false,'30/04/2026','30/04/2026',false,'30/04/2026','30/04/2026',79,4,0,0,0,0,0,0,0,'','','','',0,'','','',349,null,null,1,10,null,0


-- exec Tramite.paListarExpedientePendienteJefaturaPorRecibirFosCad
-- @pConFiltroFecha=0,
-- @pFechaInicio='30/04/2026',
-- @pFechaFin='30/04/2026',
-- @pConFiltroFechaMovimiento=0,
-- @pFechaInicioMovimiento='30/04/2026',
-- @pFechaFinMovimiento='30/04/2026',
-- @pIdArea=79,
-- @pIdCatalogoSituacionMovimientoDestino=4,
-- @pTipoSituacionMovimiento=0,
-- @pIdAreaOrigen=0,
-- @pIdAreaDestino=0,
-- @pIdPeriodo=0,
-- @pIdCatalogoTipoPrioridad=0,
-- @pIdCatalogoTipoTramite=0,
-- @pIdCatalogoTipoDocumento=0,
-- @pNumeroExpediente='',
-- @pNumeroDocumento='',
-- @pPersonaDesde='',
-- @pPersonaPara='',
-- @pIdTipoIngreso=0,
-- @pFechaDocumento='',
-- @pEmisorExpediente='',
-- @pAsuntoExpediente='',
-- @pIdUsuarioAuditoria=349,
-- @pCampoOrdenado=NULL,
-- @pTipoOrdenacion=NULL,
-- @pNumeroPagina=1,
-- @pDimensionPagina=10,
-- @pBusquedaGeneral=NULL,
-- @pFlgBusqueda=0


-- exec Tramite.paListarExpedientePendienteJefaturaPorRecibirFosCad_new
-- @pConFiltroFecha=0,
-- @pFechaInicio='29/04/2026',
-- @pFechaFin='29/04/2026',
-- @pConFiltroFechaMovimiento=0,
-- @pFechaInicioMovimiento='29/04/2026',
-- @pFechaFinMovimiento='29/04/2026',
-- @pIdArea=24,
-- @pIdCatalogoSituacionMovimientoDestino=4,
-- @pTipoSituacionMovimiento=4,
-- @pIdAreaOrigen=0,
-- @pIdAreaDestino=0,
-- @pIdPeriodo=2026,
-- @pIdCatalogoTipoPrioridad=0,
-- @pIdCatalogoTipoTramite=0,
-- @pIdCatalogoTipoDocumento=0,
-- @pNumeroExpediente='',
-- @pNumeroDocumento='',
-- @pPersonaDesde='',
-- @pPersonaPara='',
-- @pIdTipoIngreso=0,
-- @pFechaDocumento='',
-- @pEmisorExpediente='',
-- @pAsuntoExpediente='',
-- @pIdUsuarioAuditoria=790,
-- @pCampoOrdenado=NULL,
-- @pTipoOrdenacion=NULL,
-- @pNumeroPagina=1,
-- @pDimensionPagina=10,
-- @pBusquedaGeneral=NULL,
-- @pFlgBusqueda=0


-- NUEVO

exec Tramite.paListarExpedientePendienteJefaturaPorRecibirFosCad
@pConFiltroFecha=0,
@pFechaInicio='30/04/2026',
@pFechaFin='30/04/2026',
@pConFiltroFechaMovimiento=0,
@pFechaInicioMovimiento='30/04/2026',
@pFechaFinMovimiento='30/04/2026',
@pIdArea=24,
@pIdCatalogoSituacionMovimientoDestino=4,
@pTipoSituacionMovimiento=4,
@pIdAreaOrigen=0,
@pIdAreaDestino=0,
@pIdPeriodo=2026,
@pIdCatalogoTipoPrioridad=0,
@pIdCatalogoTipoTramite=0,
@pIdCatalogoTipoDocumento=0,
@pNumeroExpediente='',
@pNumeroDocumento='',
@pPersonaDesde='',
@pPersonaPara='',
@pIdTipoIngreso=0,
@pFechaDocumento='',
@pEmisorExpediente='',
@pAsuntoExpediente='',
@pIdUsuarioAuditoria=790,
@pCampoOrdenado=NULL,
@pTipoOrdenacion=NULL,
@pNumeroPagina=1,
@pDimensionPagina=10,
@pBusquedaGeneral=NULL,
@pFlgBusqueda=0



exec [Tramite].[paListarExpedientePendienteJefaturaPorRecibirFosCad]
@pConFiltroFecha = 0,
@pFechaInicio = '15/04/2026',
@pFechaFin = '15/04/2026',
@pConFiltroFechaMovimiento = 0,
@pFechaInicioMovimiento = '15/04/2026',
@pFechaFinMovimiento = '15/04/2026',
@pIdArea = 30,
@pIdCatalogoSituacionMovimientoDestino = 4,
@pTipoSituacionMovimiento = 0,
@pIdAreaOrigen = 0,
@pIdAreaDestino = 0,
@pIdPeriodo = 0,
@pIdCatalogoTipoPrioridad = 0,
@pIdCatalogoTipoTramite = 0,
@pIdCatalogoTipoDocumento = 0,
@pNumeroExpediente = '',
@pNumeroDocumento = '',
@pPersonaDesde = '',
@pPersonaPara = '',
@pIdTipoIngreso = 0,
@pFechaDocumento = '',
@pEmisorExpediente = '',
@pAsuntoExpediente = '',
@pIdUsuarioAuditoria = 52939,
@pCampoOrdenado = null,
@pTipoOrdenacion = null,
@pNumeroPagina = 1,
@pDimensionPagina = 10,
@pBusquedaGeneral = null,
@pFlgBusqueda = 0


-- exec [Tramite].[paListarExpedientePendienteJefaturaPorRecibirFosCad_new]
-- @pConFiltroFecha = 0,
-- @pFechaInicio = '15/04/2026',
-- @pFechaFin = '15/04/2026',
-- @pConFiltroFechaMovimiento = 0,
-- @pFechaInicioMovimiento = '15/04/2026',
-- @pFechaFinMovimiento = '15/04/2026',
-- @pIdArea = 30,
-- @pIdCatalogoSituacionMovimientoDestino = 4,
-- @pTipoSituacionMovimiento = 0,
-- @pIdAreaOrigen = 0,
-- @pIdAreaDestino = 0,
-- @pIdPeriodo = 0,
-- @pIdCatalogoTipoPrioridad = 0,
-- @pIdCatalogoTipoTramite = 0,
-- @pIdCatalogoTipoDocumento = 0,
-- @pNumeroExpediente = '',
-- @pNumeroDocumento = '',
-- @pPersonaDesde = '',
-- @pPersonaPara = '',
-- @pIdTipoIngreso = 0,
-- @pFechaDocumento = '',
-- @pEmisorExpediente = '',
-- @pAsuntoExpediente = '',
-- @pIdUsuarioAuditoria = 52939,
-- @pCampoOrdenado = null,
-- @pTipoOrdenacion = null,
-- @pNumeroPagina = 1,
-- @pDimensionPagina = 10,
-- @pBusquedaGeneral = null,
-- @pFlgBusqueda = 0


 -- -- Tramite.paListarExpedienteMesaParteDespachadosV1
 -- select
 -- @pIdArea=20,
 -- @pIdUsuarioAuditoria=389,
 -- @pCampoOrdenado=NULL,
 -- @pTipoOrdenacion=NULL,
 -- @pNumeroPagina=1,
 -- @pDimensionPagina=10,
 -- @pBusquedaGeneral=NULL

 -- -- Tramite.paListarExpedienteMesaParteDespachadosV1 20, 389,null, null, 1,10,null



 -- -- [Tramite].[paListarExpedientePendienteEspecialistaCreados]
 -- select
	-- @pConFiltroFecha = 0,
	-- @pFechaInicio = '13/04/2026',
	-- @pFechaFin = '13/04/2026',
	-- @pConFiltroFechaMovimiento = 0,
	-- @pFechaInicioMovimiento = '13/04/2026',
	-- @pFechaFinMovimiento = '13/04/2026',
	-- @pIdPersona = 728,
	-- @pIdEmpleadoPerfil = 727,
	-- @pIdCatalogoSituacionMovimientoDestino = 116,
	-- @pTipoSituacionMovimiento = 4,
	-- @pIdAreaOrigen = 0,
 --    @pIdAreaDestino = 0,
 --    @pIdPeriodo = 2026,
 --    @pIdCatalogoTipoPrioridad = 0,
 --    @pIdCatalogoTipoTramite = 0,
 --    @pIdCatalogoTipoDocumento = 0,
 --    @pNumeroExpediente = '',
 --    @pNumeroDocumento = '',
	-- @pPersonaDesde = '',
	-- @pPersonaPara = '',
	-- @pIdTipoIngreso = 0,
	-- @pFechaDocumento  = '',
	-- @pEmisorExpediente = '',
	-- @pAsuntoExpediente  = '',
	-- @pIdUsuarioAuditoria = 728,
	-- @pCampoOrdenado = null,
	-- @pTipoOrdenacion = null,
	-- @pNumeroPagina = 1,
	-- @pDimensionPagina = 10,
	-- @pBusquedaGeneral = null,
	-- @pFlgBusqueda = 0
