
-- CREATE PROCEDURE [Tramite].[paListarExpedientePendienteEspecialistaPorRecibir]
DECLARE
	@pConFiltroFecha bit,
	@pFechaInicio varchar(10),
	@pFechaFin varchar(10),
	@pConFiltroFechaMovimiento bit,
	@pFechaInicioMovimiento varchar(10),
	@pFechaFinMovimiento varchar(10),
	@pIdPersona int,
	@pIdEmpleadoPerfil int,
	@pIdCatalogoSituacionMovimientoDestino INT,
	@pTipoSituacionMovimiento int,
	@pIdAreaOrigen int,
    @pIdAreaDestino int,
    @pIdPeriodo int,
    @pIdCatalogoTipoPrioridad int,
    @pIdCatalogoTipoTramite int,
    @pIdCatalogoTipoDocumento int,
    @pNumeroExpediente varchar(100),
    @pNumeroDocumento varchar(100),
	@pPersonaDesde varchar(100),
	@pPersonaPara varchar(100),
	@pIdTipoIngreso int,
	@pFechaDocumento  varchar(100),
	@pEmisorExpediente varchar(100),
	@pAsuntoExpediente  varchar(100),
	@pIdUsuarioAuditoria int,
	@pCampoOrdenado varchar(50),
	@pTipoOrdenacion varchar(4),
	@pNumeroPagina INT,
	@pDimensionPagina  INT,
	@pBusquedaGeneral varchar(100),
	@pFlgBusqueda INT

SELECT
@pConFiltroFecha=0,
@pFechaInicio='13/04/2026',
@pFechaFin='13/04/2026',
@pConFiltroFechaMovimiento=0,
@pFechaInicioMovimiento='13/04/2026',
@pFechaFinMovimiento='13/04/2026',
@pIdPersona=590,
@pIdEmpleadoPerfil=588,
@pIdCatalogoSituacionMovimientoDestino=4,
@pTipoSituacionMovimiento=4,
@pIdAreaOrigen=0,
@pIdAreaDestino=0,
@pIdPeriodo=2026,
@pIdCatalogoTipoPrioridad=0,
@pIdCatalogoTipoTramite=0,
@pIdCatalogoTipoDocumento=0,
@pNumeroExpediente='',
@pNumeroDocumento='',
@pPersonaDesde='',
@pPersonaPara='',
@pIdTipoIngreso=0,
@pFechaDocumento='',
@pEmisorExpediente='',
@pAsuntoExpediente='',
@pIdUsuarioAuditoria=590,
@pCampoOrdenado=NULL,
@pTipoOrdenacion=NULL,
@pNumeroPagina=1,
@pDimensionPagina=100,
@pBusquedaGeneral=NULL,
@pFlgBusqueda=0

select
    @pConFiltroFecha= 0,
	@pFechaInicio= '10/04/2026',
	@pFechaFin= '10/04/2026',
	@pConFiltroFechaMovimiento= 0,
	@pFechaInicioMovimiento= '10/04/2026',
	@pFechaFinMovimiento= '10/04/2026',
	@pIdPersona= 1059,
	@pIdEmpleadoPerfil= 2259,
	@pIdCatalogoSituacionMovimientoDestino= 4,
	@pTipoSituacionMovimiento= 4,
	@pIdAreaOrigen= 0,
	@pIdAreaDestino= 0,
	@pIdPeriodo= 2026,
	@pIdCatalogoTipoPrioridad= 0,
	@pIdCatalogoTipoTramite= 0,
	@pIdCatalogoTipoDocumento= 0,
	@pNumeroExpediente= '',
	@pNumeroDocumento= '',
	@pPersonaDesde= '',
	@pPersonaPara= '',
	@pIdTipoIngreso= 0,
	@pFechaDocumento= '',
	@pEmisorExpediente= '',
	@pAsuntoExpediente= '',
	@pIdUsuarioAuditoria= 1059,
	@pCampoOrdenado= null,
	@pTipoOrdenacion= null,
	@pNumeroPagina= 1,
	@pDimensionPagina= 10,
	@pBusquedaGeneral= null,
	@pFlgBusqueda= 0
