exec Tramite.paListarExpedientePendienteEspecialistaV7
@pConFiltroFecha=0,
@pFechaInicio='05/05/2026',
@pFechaFin='05/05/2026',
@pConFiltroFechaMovimiento=0,
@pFechaInicioMovimiento='05/05/2026',
@pFechaFinMovimiento='05/05/2026',
@pIdPersona=965,
@pIdEmpleadoPerfil=964,
@pIdCatalogoSituacionMovimientoDestino=5,
@pTipoSituacionMovimiento=4,
@pIdAreaOrigen=0,
@pIdAreaDestino=0,
@pIdPeriodo=2026,
@pIdCatalogoTipoPrioridad=0,
@pIdCatalogoTipoTramite=0,
@pIdCatalogoTipoDocumento=0,
@pNumeroExpediente='',
@pNumeroDocumento='',
@pPersonaDesde='',
@pPersonaPara='',
@pIdTipoIngreso=0,
@pFechaDocumento='',
@pEmisorExpediente='',
@pAsuntoExpediente='',
@pIdUsuarioAuditoria=965,
@pCampoOrdenado=NULL,
@pTipoOrdenacion=NULL,
@pNumeroPagina=1,
@pDimensionPagina=10,
@pBusquedaGeneral=NULL,
@pFlgBusqueda=0

exec Tramite.paListarExpedientePendienteEspecialistaV7_new
@pConFiltroFecha=0,
@pFechaInicio='05/05/2026',
@pFechaFin='05/05/2026',
@pConFiltroFechaMovimiento=0,
@pFechaInicioMovimiento='05/05/2026',
@pFechaFinMovimiento='05/05/2026',
@pIdPersona=965,
@pIdEmpleadoPerfil=964,
@pIdCatalogoSituacionMovimientoDestino=5,
@pTipoSituacionMovimiento=4,
@pIdAreaOrigen=0,
@pIdAreaDestino=0,
@pIdPeriodo=2026,
@pIdCatalogoTipoPrioridad=0,
@pIdCatalogoTipoTramite=0,
@pIdCatalogoTipoDocumento=0,
@pNumeroExpediente='',
@pNumeroDocumento='',
@pPersonaDesde='',
@pPersonaPara='',
@pIdTipoIngreso=0,
@pFechaDocumento='',
@pEmisorExpediente='',
@pAsuntoExpediente='',
@pIdUsuarioAuditoria=965,
@pCampoOrdenado=NULL,
@pTipoOrdenacion=NULL,
@pNumeroPagina=1,
@pDimensionPagina=10,
@pBusquedaGeneral=NULL,
@pFlgBusqueda=0



exec Tramite.paListarExpedientePendienteEspecialistaCreados
@pConFiltroFecha=0,
@pFechaInicio='05/05/2026',
@pFechaFin='05/05/2026',
@pConFiltroFechaMovimiento=0,
@pFechaInicioMovimiento='05/05/2026',
@pFechaFinMovimiento='05/05/2026',
@pIdPersona=965,
@pIdEmpleadoPerfil=964,
@pIdCatalogoSituacionMovimientoDestino=116,
@pTipoSituacionMovimiento=4,
@pIdAreaOrigen=0,
@pIdAreaDestino=0,
@pIdPeriodo=2026,
@pIdCatalogoTipoPrioridad=0,
@pIdCatalogoTipoTramite=0,
@pIdCatalogoTipoDocumento=0,
@pNumeroExpediente='',
@pNumeroDocumento='',
@pPersonaDesde='',
@pPersonaPara='',
@pIdTipoIngreso=0,
@pFechaDocumento='',
@pEmisorExpediente='',
@pAsuntoExpediente='',
@pIdUsuarioAuditoria=965,
@pCampoOrdenado=NULL,
@pTipoOrdenacion=NULL,
@pNumeroPagina=1,
@pDimensionPagina=10,
@pBusquedaGeneral=NULL,
@pFlgBusqueda=0


exec Tramite.paListarExpedientePendienteEspecialistaCreados_new
@pConFiltroFecha=0,
@pFechaInicio='05/05/2026',
@pFechaFin='05/05/2026',
@pConFiltroFechaMovimiento=0,
@pFechaInicioMovimiento='05/05/2026',
@pFechaFinMovimiento='05/05/2026',
@pIdPersona=965,
@pIdEmpleadoPerfil=964,
@pIdCatalogoSituacionMovimientoDestino=116,
@pTipoSituacionMovimiento=4,
@pIdAreaOrigen=0,
@pIdAreaDestino=0,
@pIdPeriodo=2026,
@pIdCatalogoTipoPrioridad=0,
@pIdCatalogoTipoTramite=0,
@pIdCatalogoTipoDocumento=0,
@pNumeroExpediente='',
@pNumeroDocumento='',
@pPersonaDesde='',
@pPersonaPara='',
@pIdTipoIngreso=0,
@pFechaDocumento='',
@pEmisorExpediente='',
@pAsuntoExpediente='',
@pIdUsuarioAuditoria=965,
@pCampoOrdenado=NULL,
@pTipoOrdenacion=NULL,
@pNumeroPagina=1,
@pDimensionPagina=10,
@pBusquedaGeneral=NULL,
@pFlgBusqueda=0



exec Tramite.paObtenerEstadosExpedientesEspecialista
@pIdPersona=965,
@pIdEmpleadoPerfil=964,
@pIdUsuarioAuditoria=965

exec Tramite.paObtenerEstadosExpedientesEspecialista_new
@pIdPersona=965,
@pIdEmpleadoPerfil=964,
@pIdUsuarioAuditoria=965




exec Tramite.paListarExpedientePendienteEspecialistaV7
@pConFiltroFecha=0,
@pFechaInicio='05/05/2026',
@pFechaFin='05/05/2026',
@pConFiltroFechaMovimiento=0,
@pFechaInicioMovimiento='05/05/2026',
@pFechaFinMovimiento='05/05/2026',
@pIdPersona=965,
@pIdEmpleadoPerfil=964,
@pIdCatalogoSituacionMovimientoDestino=5,
@pTipoSituacionMovimiento=4,
@pIdAreaOrigen=0,
@pIdAreaDestino=0,
@pIdPeriodo=2026,
@pIdCatalogoTipoPrioridad=0,
@pIdCatalogoTipoTramite=0,
@pIdCatalogoTipoDocumento=0,
@pNumeroExpediente='',
@pNumeroDocumento='',
@pPersonaDesde='',
@pPersonaPara='',
@pIdTipoIngreso=0,
@pFechaDocumento='',
@pEmisorExpediente='',
@pAsuntoExpediente='',
@pIdUsuarioAuditoria=965,
@pCampoOrdenado=NULL,
@pTipoOrdenacion=NULL,
@pNumeroPagina=1,
@pDimensionPagina=10,
@pBusquedaGeneral=NULL,
@pFlgBusqueda=0


exec Tramite.paListarExpedientePendienteEspecialistaV7_new
@pConFiltroFecha=0,
@pFechaInicio='05/05/2026',
@pFechaFin='05/05/2026',
@pConFiltroFechaMovimiento=0,
@pFechaInicioMovimiento='05/05/2026',
@pFechaFinMovimiento='05/05/2026',
@pIdPersona=965,
@pIdEmpleadoPerfil=964,
@pIdCatalogoSituacionMovimientoDestino=5,
@pTipoSituacionMovimiento=4,
@pIdAreaOrigen=0,
@pIdAreaDestino=0,
@pIdPeriodo=2026,
@pIdCatalogoTipoPrioridad=0,
@pIdCatalogoTipoTramite=0,
@pIdCatalogoTipoDocumento=0,
@pNumeroExpediente='',
@pNumeroDocumento='',
@pPersonaDesde='',
@pPersonaPara='',
@pIdTipoIngreso=0,
@pFechaDocumento='',
@pEmisorExpediente='',
@pAsuntoExpediente='',
@pIdUsuarioAuditoria=965,
@pCampoOrdenado=NULL,
@pTipoOrdenacion=NULL,
@pNumeroPagina=1,
@pDimensionPagina=10,
@pBusquedaGeneral=NULL,
@pFlgBusqueda=0




exec Tramite.paListarExpedientePendienteEspecialistaReenviados
@pConFiltroFecha=0,
@pFechaInicio='05/05/2026',
@pFechaFin='05/05/2026',
@pConFiltroFechaMovimiento=0,
@pFechaInicioMovimiento='05/05/2026',
@pFechaFinMovimiento='05/05/2026',
@pIdPersona=965,
@pIdEmpleadoPerfil=964,
@pIdCatalogoSituacionMovimientoDestino=111,
@pTipoSituacionMovimiento=4,
@pIdAreaOrigen=0,
@pIdAreaDestino=0,
@pIdPeriodo=2026,
@pIdCatalogoTipoPrioridad=0,
@pIdCatalogoTipoTramite=0,
@pIdCatalogoTipoDocumento=0,
@pNumeroExpediente='',
@pNumeroDocumento='',
@pPersonaDesde='',
@pPersonaPara='',
@pIdTipoIngreso=0,
@pFechaDocumento='',
@pEmisorExpediente='',
@pAsuntoExpediente='',
@pIdUsuarioAuditoria=965,
@pCampoOrdenado=NULL,
@pTipoOrdenacion=NULL,
@pNumeroPagina=1,
@pDimensionPagina=10,
@pBusquedaGeneral=NULL,
@pFlgBusqueda=0


exec Tramite.paListarExpedientePendienteEspecialistaReenviados_new
@pConFiltroFecha=0,
@pFechaInicio='05/05/2026',
@pFechaFin='05/05/2026',
@pConFiltroFechaMovimiento=0,
@pFechaInicioMovimiento='05/05/2026',
@pFechaFinMovimiento='05/05/2026',
@pIdPersona=965,
@pIdEmpleadoPerfil=964,
@pIdCatalogoSituacionMovimientoDestino=111,
@pTipoSituacionMovimiento=4,
@pIdAreaOrigen=0,
@pIdAreaDestino=0,
@pIdPeriodo=2026,
@pIdCatalogoTipoPrioridad=0,
@pIdCatalogoTipoTramite=0,
@pIdCatalogoTipoDocumento=0,
@pNumeroExpediente='',
@pNumeroDocumento='',
@pPersonaDesde='',
@pPersonaPara='',
@pIdTipoIngreso=0,
@pFechaDocumento='',
@pEmisorExpediente='',
@pAsuntoExpediente='',
@pIdUsuarioAuditoria=965,
@pCampoOrdenado=NULL,
@pTipoOrdenacion=NULL,
@pNumeroPagina=1,
@pDimensionPagina=10,
@pBusquedaGeneral=NULL,
@pFlgBusqueda=0
