ALTER PROCEDURE Tramite.paGuardarExpedienteSeguimiento
ALTER PROCEDURE Tramite.paEliminarExpedienteSeguimiento
ALTER PROCEDURE Tramite.paListarPeriodoBusquedaDocumentoJefatura
ALTER PROCEDURE Tramite.paListarPeriodoBusquedaDocumentoEspecialista
ALTER PROCEDURE Tramite.paListarPeriodoBusquedaExpediente  ++++

ALTER PROCEDURE Tramite.paListarDocumentoHojaRuta_BusquedaGeneral_arq
ALTER PROCEDURE Tramite.paGuardarReenviarExpedienteDocumentoReenvioMasivoEspecialista
ALTER PROCEDURE Tramite.paExtornarPendienteJefatura
ALTER PROCEDURE Tramite.paGuardarRecibirExpedienteDocumentoEspecialista
ALTER PROCEDURE Tramite.paExtornarRecepcionPendienteEspecialista
ALTER PROCEDURE Tramite.paGuardarReenviarExpedienteDocumentoJefaturaV2
